name: Build and Push Docker Image

on:
  push:
    # branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME is derived from the repository owner and a fixed name 'tofuboi'
  IMAGE_NAME: ${{ github.repository_owner }}/tofuboi

jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm

    permissions:
      contents: read
      packages: write # Needed to push cache and image to ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} # Use the defined IMAGE_NAME

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Use ghcr.io for caching
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:build-cache
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # Push cache to ghcr.io, use mode=max for better caching
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:build-cache,mode=max
